### ISSUE TITLE
Need Some Help !

### ISSUE THREAD

**Issue by ghost** [kmoulart/Pacman-CPlusPlus#1]
@kmoulart Can you please tell me which 3d software was used in creating the 3d models? And can you please share the original models with me. i am trying to do something similar like you. i would be very happy if you help me :)

**Comment by kmoulart** [comment]
Hi @amibappy ,

I don't really remember how I generated the 3D code to use in C++ but I used Sketchup for the 3D modeling and found the models in their 3D Warehouse (all free).

All used models are in the project, feel free to use them for your personal use.

Hope this helps,
Kind regards,
Kévin

**Comment by ghost** [comment]
Thank you Kévin @kmoulart  for your reply :) i think you have already helped me a lot. You are really a good programmer & a great inspiration for newbies like me xD 

Thanks Again,
Bappy
